// List of Indian festivals with their dates for each year
// Add more festivals as needed
export const FESTIVALS_BY_YEAR = {
    2025: [
        { name: 'Diwali', month: 10, day: 21 },
        { name: 'Holi', month: 3, day: 14 },
        { name: 'Christmas', month: 12, day: 25 },
        { name: 'Eid', month: 3, day: 31 },
        { name: 'Raksha Bandhan', month: 8, day: 8 },
        { name: 'Independence Day', month: 8, day: 15 },
        { name: 'New Year', month: 1, day: 1 },
        { name: 'Pongal', month: 1, day: 15 },
        { name: 'Ganesh Chaturthi', month: 8, day: 27 },
        { name: 'Navratri', month: 9, day: 22 },
        { name: 'Makar Sankranti', month: 1, day: 14 },
        { name: 'Lohri', month: 1, day: 13 },
        { name: 'Onam', month: 9, day: 5 },
        { name: 'Janmashtami', month: 8, day: 16 },
        { name: 'Baisakhi', month: 4, day: 13 },
        { name: 'Gudi Padwa', month: 3, day: 30 },
        { name: 'Mahavir Jayanti', month: 4, day: 10 },
        { name: 'Good Friday', month: 4, day: 18 },
        { name: 'Guru Nanak Jayanti', month: 11, day: 5 },
        { name: 'Dussehra', month: 10, day: 2 },
        { name: 'Karva Chauth', month: 10, day: 30 },
        { name: 'Bhai Dooj', month: 10, day: 23 },
        { name: 'Chhath Puja', month: 10, day: 27 }
    ],
    2026: [
        { name: 'Diwali', month: 11, day: 8 },
        { name: 'Holi', month: 3, day: 4 },
        { name: 'Christmas', month: 12, day: 25 },
        { name: 'Eid', month: 3, day: 20 },
        { name: 'Raksha Bandhan', month: 8, day: 28 },
        { name: 'Independence Day', month: 8, day: 15 },
        { name: 'New Year', month: 1, day: 1 },
        { name: 'Pongal', month: 1, day: 15 },
        { name: 'Ganesh Chaturthi', month: 9, day: 16 },
        { name: 'Navratri', month: 10, day: 11 },
        { name: 'Makar Sankranti', month: 1, day: 14 },
        { name: 'Lohri', month: 1, day: 13 },
        { name: 'Onam', month: 8, day: 25 },
        { name: 'Janmashtami', month: 9, day: 5 },
        { name: 'Baisakhi', month: 4, day: 13 },
        { name: 'Gudi Padwa', month: 3, day: 20 },
        { name: 'Mahavir Jayanti', month: 4, day: 29 },
        { name: 'Good Friday', month: 4, day: 3 },
        { name: 'Guru Nanak Jayanti', month: 11, day: 24 },
        { name: 'Dussehra', month: 10, day: 22 },
        { name: 'Karva Chauth', month: 10, day: 19 },
        { name: 'Bhai Dooj', month: 11, day: 10 },
        { name: 'Chhath Puja', month: 11, day: 13 }
    ]
};
